### PR TITLE
Custom driver search prepend documentation

### LINKED ISSUE #889: Duffle driver documentation - prepending 'duffle-'
There might be a different issue out there but wanted to call this out for record sake.

https://github.com/cnabio/duffle/blob/master/docs/proposal/202-drivers.md#custom-drivers
"prepending duffle- to the driver name"

Duffle uses the cnab-go lib for this, which actually applies "cnab-"

https://github.com/cnabio/cnab-go/blob/af30b09b45da1b93ca09bc54349d93e661786b6d/driver/command/command.go#L45

### PR DESCRIPTION
**Pull request by BenWhiting**
Updating docs with new behavior expecting "cnab-" instead of "duffle-".

Fixes #889

### CODE REVIEW

**Comment by glyn** [comment]
It's handy to link PRs to issues e.g. by putting something like the following in the commit log.

Fixes https://github.com/cnabio/duffle/issues/889

**Comment by BenWhiting** [comment]
> It's handy to link PRs to issues e.g. by putting something like the following in the commit log.
> 
> Fixes #889

Will do! Would you like me to amend the commit message?
I thought I put it in the PR comment but apparently I didn't.

**Comment by glyn** [comment]
> Will do! Would you like me to amend the commit message?

If you like, for the practice, but no pressure!

> I thought I put it in the PR comment but apparently I didn't.

github was playing up yesterday, so I wonder if it's going pear-shaped again? But apparently not according to https://www.githubstatus.com/.

**Comment by carolynvs** [comment]
I added the fixed issue to the PR comment. I don't know if that's required but why not? 😀

**Comment by carolynvs** [comment]
@vdice Can you look at why the tests didn't kick off or report back to github? I think GH is acting up, so it may be that.

**Comment by carolynvs** [comment]
Sweet! I completely forgot about `/brig run`. 💯 Thanks @vdice Next time I'll know how to kick it myself without pestering you.

**Pull request merged**
